// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqNoP8bVAzihf_oADjr6sd-j_8PhRWhs',
    appId: '1:819176537141:web:284bb236132ecc0b53857c',
    messagingSenderId: '819176537141',
    projectId: 'pharmascan-2025',
    authDomain: 'pharmascan-2025.firebaseapp.com',
    storageBucket: 'pharmascan-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnX9gtprfn01PUQkqUMZp414yPkFgSOEY',
    appId: '1:819176537141:android:70f4acec9c79d3d853857c',
    messagingSenderId: '819176537141',
    projectId: 'pharmascan-2025',
    storageBucket: 'pharmascan-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UA-ehU2klzXwC-D0f_A69SXukIb_5bw',
    appId: '1:819176537141:ios:7ad449b9d676ea3e53857c',
    messagingSenderId: '819176537141',
    projectId: 'pharmascan-2025',
    storageBucket: 'pharmascan-2025.firebasestorage.app',
    iosBundleId: 'com.example.pharmascanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UA-ehU2klzXwC-D0f_A69SXukIb_5bw',
    appId: '1:819176537141:ios:7ad449b9d676ea3e53857c',
    messagingSenderId: '819176537141',
    projectId: 'pharmascan-2025',
    storageBucket: 'pharmascan-2025.firebasestorage.app',
    iosBundleId: 'com.example.pharmascanApp',
  );

}